
labels: {}

image:
  repository: slok/sloth
  tag: v0.8.0

sloth:
  resyncInterval: ""  # The controller resync interval duration (e.g 15m).
  workers: 0          # The number of concurrent controller workers (e.g 5).
  labelSelector: ""   # Sloth will handle only the ones that match the selector.
  namespace: ""       # The namespace where sloth will the CRs to process.
  extraLabels: {}     # Labels that will be added to all the generated SLO Rules.

commonPlugins:
  enabled: true
  gitRepo:
    url: https://github.com/slok/sloth-common-sli-plugins
    branch: main

metrics:
  enabled: true
  prometheusLabels: {}
